//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserAddress
    {
        public int Id { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string State { get; set; }
        [Required]
        public string Zip { get; set; }
        [Required]
        public string UserName { get; set; }

        public string userId { get; set; }

        public UserAddress(string userName)
        {
            this.UserName = userName;

        }
        
        public UserAddress(string userName, string addr, string city, string state, string zip , string id)
        {
            this.UserName = userName;
            this.Address = addr;
            this.City = city;
            this.State = state;
            this.Zip = zip;
            this.userId = id;
        }

        public UserAddress() { }
    }
}
